# The rpc address of the chain node
RpcAddr     = "wss://testnet-rpc0.cess.cloud/ws/"
# Port number monitored by the scheduler program
ServicePort = "15000"
# Data storage directory
DataDir     = "."
# Phrase or seed of the controller account
AccountSeed = "swear theme bounce soccer hungry gesture hurdle asset typical call balcony wrist"
