# The rpc address of the chain node
RpcAddr     = "wss://testnet-rpc0.cess.cloud/ws/"
# The IP address of the machine's public network used by the scheduler program
ServiceAddr = "127.0.0.1"
# Port number monitored by the scheduler program
ServicePort = "15000"
# Data storage directory
DataDir     = "."
# Phrase or seed of the controller account
CtrlPrk     = "swear theme bounce soccer hungry gesture hurdle asset typical call balcony wrist"
# The address of stash account
StashAcc    = "cXfg2SYcq85nyZ1U4ccx6QnAgSeLQB8aXZ2jstbw9CPGSmhXY"